"""
Synthesizer Agent — Produces the final structured markdown report.

Responsibilities:
  • Take the full research state and generate a polished markdown report.
  • Use proper inline citations referencing the sources list.
  • Include "Research Limitations" section if errors exist.
"""

from __future__ import annotations

import logging
from datetime import datetime

from langchain_core.messages import SystemMessage, HumanMessage

from config import LLM_TEMPERATURE_SYNTHESIS, LLM_MAX_TOKENS_SYNTHESIS
from state import ResearchState
from utils import get_llm

logger = logging.getLogger(__name__)

SYNTHESIZE_PROMPT = """You are an expert research report writer. Using the research data below, 
produce a comprehensive, well-structured markdown report.

Topic: {topic}

Web Research Results:
{web_results}

Academic Paper Results:
{paper_results}

{critique_section}

{errors_section}

REPORT FORMAT — follow this structure exactly:

# Research Report: {topic}
*Generated by Multi-Agent Research Assistant | {timestamp}*

## Executive Summary
3–5 sentence overview of the topic and key findings.

## Key Findings
- Finding one [1]
- Finding two [2, 3]
(use numbered inline citations referencing the Sources section)

## Academic Perspective
Summary of what recent papers say, methodology notes, and research trends.

## Current Landscape
What's happening in industry and practice right now, based on web sources.

## Open Questions & Gaps
What remains unresolved or debated.

{limitations_section}

## Sources
[1] Title — URL
[2] ArXiv:XXXX.XXXXX — Title
(number every source used in the report)

RULES:
- Use inline citations like [1], [2, 3] throughout the report.
- Every claim must be backed by at least one source.
- Be specific and informative, not vague.
- The report should be 800-1500 words.
- Write in a professional, accessible tone.
- Return ONLY the markdown report, no other text."""


def synthesizer_node(state: ResearchState) -> dict:
    """LangGraph node: generates the final research report."""

    llm = get_llm(
        temperature=LLM_TEMPERATURE_SYNTHESIS,
        max_tokens=LLM_MAX_TOKENS_SYNTHESIS,
    )

    web_results = state.get("web_results", [])
    paper_results = state.get("paper_results", [])
    errors = state.get("errors", [])
    critique = state.get("critique", {})

    # Format web results for the prompt
    web_text = "\n".join(
        f"- Title: {r.get('title', 'Untitled')}\n  URL: {r.get('url', '')}\n  Content: {r.get('snippet', '')[:300]}"
        for r in web_results
    ) or "No web results available."

    # Format paper results
    paper_text = "\n".join(
        f"- Title: {r.get('title', 'Untitled')}\n  ArXiv: {r.get('arxiv_id', '')}\n  Summary: {r.get('summary', '')[:300]}\n  Findings: {', '.join(r.get('key_findings', []))}"
        for r in paper_results
    ) or "No academic papers found."

    # Critique section
    critique_section = ""
    if critique:
        gaps = critique.get("gaps", [])
        contradictions = critique.get("contradictions", [])
        critique_section = f"""Research Critique (quality score: {critique.get('quality_score', 'N/A')}/10):
Gaps: {', '.join(gaps) if gaps else 'None identified'}
Contradictions: {', '.join(contradictions) if contradictions else 'None identified'}"""

    # Errors / limitations
    errors_section = ""
    limitations_section = ""
    if errors:
        errors_section = f"Errors encountered during research:\n" + "\n".join(f"- {e}" for e in errors)
        limitations_section = "## Research Limitations\nInclude a note about sources that could not be retrieved."

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M")

    response = llm.invoke([
        SystemMessage(content="You are an expert research report writer."),
        HumanMessage(content=SYNTHESIZE_PROMPT.format(
            topic=state["topic"],
            web_results=web_text,
            paper_results=paper_text,
            critique_section=critique_section,
            errors_section=errors_section,
            limitations_section=limitations_section,
            timestamp=timestamp,
        )),
    ])

    logger.info("Synthesizer produced report of %d characters", len(response.content))
    return {
        "final_report": response.content,
        "status": "done",
    }
